---
name: Push to DockerHub & GHCR

on:
  workflow_call:
    inputs:
      version:
        description: 'Binary version (release tag)'
        required: true
        type: string
        default: 'latest'
      docker_tag:
        description: 'Docker image version (tag)'
        required: false
        type: string
        default: ''
      publish:
        description: 'Publish the Docker image'
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      version:
        description: 'Binary version (release tag)'
        required: true
        type: string
        default: 'latest'
      docker_tag:
        description: 'Docker image version (tag)'
        required: false
        type: string
        default: ''
      publish:
        description: 'Publish the Docker image'
        required: false
        type: boolean
        default: true

env:
  DOCKERHUB_REPO: germainlefebvre4/cvwonder
  GHCR_REPO: ghcr.io/germainlefebvre4/cvwonder
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set versions
        id: versions
        shell: bash
        run: |
          # Use docker_tag if provided, otherwise fall back to version
          docker_tag="${{ inputs.docker_tag }}"
          if [ -z "$docker_tag" ]; then
            docker_tag="${{ inputs.version }}"
          fi

          # Normalize docker_tag
          # Add 'v' prefix if in format X.Y.Z
          if [[ $docker_tag =~ ^[0-9]+(\.[0-9]+){2}$ ]]; then
            docker_tag="v$docker_tag"
          fi
          
          # Normalize cvwonder_version
          ## Remove 'v' prefix if in format vX.Y.Z
          cvwonder_version="${{ inputs.version }}"
          if [[ $cvwonder_version =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            cvwonder_version="${cvwonder_version:1}"
          fi

          # Output results
          echo "DOCKER_TAG=$docker_tag" >> $GITHUB_OUTPUT
          echo "DOCKER_TAG_THREE_DIGIT=$(echo $docker_tag | cut -d '.' -f1-3)" >> $GITHUB_OUTPUT
          echo "DOCKER_TAG_TWO_DIGIT=$(echo $docker_tag | cut -d '.' -f1-2)" >> $GITHUB_OUTPUT
          echo "DOCKER_TAG_ONE_DIGIT=$(echo $docker_tag | cut -d '.' -f1)" >> $GITHUB_OUTPUT
          echo "CVWONDER_VERSION=$cvwonder_version" >> $GITHUB_OUTPUT

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}
            ${{ env.GHCR_REPO }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.PLATFORMS }}
          push: ${{ inputs.publish }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CVWONDER_VERSION=${{ steps.versions.outputs.CVWONDER_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ steps.versions.outputs.DOCKER_TAG }}
            ${{ env.DOCKERHUB_REPO }}:${{ steps.versions.outputs.DOCKER_TAG_THREE_DIGIT }}
            ${{ env.DOCKERHUB_REPO }}:${{ steps.versions.outputs.DOCKER_TAG_TWO_DIGIT }}
            ${{ env.DOCKERHUB_REPO }}:${{ steps.versions.outputs.DOCKER_TAG_ONE_DIGIT }}
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.GHCR_REPO }}:${{ steps.versions.outputs.DOCKER_TAG }}
            ${{ env.GHCR_REPO }}:${{ steps.versions.outputs.DOCKER_TAG_THREE_DIGIT }}
            ${{ env.GHCR_REPO }}:${{ steps.versions.outputs.DOCKER_TAG_TWO_DIGIT }}
            ${{ env.GHCR_REPO }}:${{ steps.versions.outputs.DOCKER_TAG_ONE_DIGIT }}
            ${{ env.GHCR_REPO }}:latest

      - name: Export digest
        if: ${{ inputs.publish }}
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"
      
      - name: Validate image integrity
        run: |
          docker run --rm ${{ env.DOCKERHUB_REPO }}:${{ steps.versions.outputs.DOCKER_TAG }} version

      - name: Upload digest
        if: ${{ inputs.publish }}
        uses: actions/upload-artifact@v4
        with:
          name: digests
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

      - name: Docker Hub Description
        if: ${{ inputs.publish }}
        uses: peter-evans/dockerhub-description@v4
        with:
          repository: ${{ env.DOCKERHUB_REPO }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./docs/dockerhub/README.md
